image:
    file: .gitpod.Dockerfile  

tasks:
  - name: pluseAudio
    init:  mkdir -p /home/gitpod/.config/pulse/ && pulseaudio -D -v
    command: brave-browser
  
ports:
  - name: vncServer
    port: 6080
    onOpen: open-preview
