image:
    file: .gitpod.Dockerfile  

tasks:
  - name: start-pulseaudio
    init: pulseaudio -D -v && pulseaudio
  - name: start-brave-browser
    command: brave-browser
  
ports:
  - name: vnc-server
    port: 6080
    onOpen: open-preview
