image:
    file: .gitpod.Dockerfile  

tasks:
  - name: start-pulseaudio
    command: pulseaudio -D -v && echo "load-module module-native-protocol-unix auth-anonymous=1" >> ~/.config/pulse/default.pa && pulseaudio --kill && pulseaudio -D -v
  - name: start-brave-browser
    command: brave-browser
  
ports:
  - name: vnc-server
    port: 6080
    onOpen: open-preview
  - name: pulseaudio
    port: 4713
    onOpen: ignore
