image:
    file: .gitpod.Dockerfile  

tasks:
  - name: pluseAudio
    init: pulseaudio --start
    command: brave-browser
  
ports:
  - name: vncServer
    port: 6080
    onOpen: open-preview
  - name: pulseAudio
    port : 5900
    onOpen: ignore
